import dynamic from 'next/dynamic';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
// import Navbar from '../components/navbar/Navbar';
// import Main from '../components/main/Main';
// import Footer from '../components/footer/Footer';

const Navbar = dynamic(() => import('../components/navbar/Navbar'));

const Main = dynamic(() => import('../components/main/Main'));

const Footer = dynamic(() => import('../components/footer/Footer'));

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pendaftaran Gunadarma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar />

      <div id="modal"></div>

      <Main />

      <Footer />
    </div>
  )
}
